name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5076c8662796757da3b6232c365503c7ae048334ecf476b5ee1c1b07e3a7b40"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
