name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c80a79651cd50cac9af6813eb26d20fc54e36aec86451918c024e707b3c68d5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
