name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1136adeb67537cd2afb801d966d0448a50bcdec6a34e17c8dbb00c72482cbdbc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
