name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b41e648cf0f640a234e737f4d622eb4453219ad142e002c8373c6a7ae34441f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
