name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "53fe055903b0d2148e0273134663062b8fdfad116cdff8cf37f7b61f9c883381"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
