name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1106d1dc1e0496b25a57a725ee980d9bf4c35e6147ebab0bcf57b1c237e28b1a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
