name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5189a31bfbb56b36aec3b259ce0fb67fffdde84637312e7c375aae7e517331c3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
