name = "GreadeV2"
author = "darkk1"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "573a4990e77b1e6b980c64a3a7e286b5263070c3387b954e8909c509051ec9ae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
